// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confidence score in `[0.0, 1.0]`.
 *
 * Default values by `ExtractorKind` (see `evidence.rs`):
 * - `Manual`:     1.00 — user entered, ground truth
 * - `Connector`:  0.95 — structured connector field
 * - `Rule`:       0.85 — deterministic extraction rule
 * - `Llm`:        0.50 — single LLM source
 * - `Calculated`: inherits from sources
 *
 * Multiple evidence items aggregate via noisy-OR:
 *   `combined = 1 - ∏(1 - evidence_i.confidence)`
 *
 * UI rendering thresholds:
 * - ≥ 0.85 → solid line, no badge
 * - 0.50–0.85 → dashed line, "inferred" badge
 * - < 0.50 → dotted line, "low confidence" badge (opt-in to display)
 */
export type Confidence = number;
