// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Confidence } from "./Confidence";
import type { EvidenceId } from "./EvidenceId";
import type { ExtractorKind } from "./ExtractorKind";
import type { NodeId } from "./NodeId";
import type { SourceType } from "./SourceType";

export type Evidence = { id: EvidenceId, source_node_id: NodeId, source_type: SourceType, quote: string | null, 
/**
 * Structured location reference. E.g. `"Sheet1!B7"` for CSV, `"p.12 §3"` for documents.
 */
row_ref: string | null, 
/**
 * SHA-256 of the corresponding blob in `blobs/<sha256>`. Used by recompute worker.
 */
blob_sha256: string | null, timestamp: string | null, extractor: ExtractorKind, confidence: Confidence, is_tainted: boolean, requires_human_review: boolean, };
