// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KpiStatus } from "./KpiStatus";
import type { KpiTrend } from "./KpiTrend";
import type { KpiUnit } from "./KpiUnit";
import type { NodeId } from "./NodeId";
import type { Period } from "./Period";

/**
 * Stored as MessagePack inside `nodes.attrs` for `NodeKind::Kpi` nodes.
 * Parsed and validated by `GraphStore::apply_mutation` on every upsert.
 */
export type KpiAttrs = { value: number | null, unit: KpiUnit, period: Period, status: KpiStatus, trend: KpiTrend, target: number | null, 
/**
 * Points to a `NodeKind::Person` or `NodeKind::Team` node.
 */
owner_node_id: NodeId | null, definition: string, 
/**
 * Points to `NodeKind::Document` nodes that are the authoritative sources.
 */
source_refs: Array<NodeId>, explanation: string | null, last_recomputed_at: string | null, };
