// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Computed by `kpi_recompute_worker`. Never set manually.
 * `Up`/`Down`/`Flat` = sign(value_t - value_{t-1}).
 */
export type KpiTrend = "Up" | "Down" | "Flat" | "Unknown";
