// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeKind = "Kpi" | "Metric" | "Objective" | "Initiative" | "Risk" | "Opportunity" | "Decision" | "Insight" | "Document" | "Person" | "Team" | "Customer" | "Function" | "Product" | "Market" | "Process" | "System" | "Action";
