// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Confidence } from "./Confidence";
import type { NodeId } from "./NodeId";
import type { NodeKind } from "./NodeKind";
import type { JsonValue } from "./serde_json/JsonValue";

export type Node = { id: NodeId, kind: NodeKind, name: string, created_at: string, updated_at: string, 
/**
 * Kind-specific payload. `NodeKind::Kpi` nodes use `KpiAttrs`; others use arbitrary JSON.
 * Stored as MessagePack BLOB in SQLite (`nodes.attrs`); JSON in transit and export.
 */
attrs: JsonValue, confidence: Confidence, is_tainted: boolean, requires_human_review: boolean, };
