// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node";
import type { NodeId } from "./NodeId";

export type AffectedNode = { node: Node, depth: number, path: Array<NodeId>, };
