// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeWithEvidence } from "./EdgeWithEvidence";
import type { Node } from "./Node";

/**
 * A pair of nodes where the graph holds contradictory claims about their relationship.
 */
export type ConflictPair = { node_a: Node, node_b: Node, 
/**
 * Edges with positive polarity (Improves, Corroborates) between the pair.
 */
positive: Array<EdgeWithEvidence>, 
/**
 * Edges with negative polarity (Degrades, Blocks, Contradicts) between the pair.
 */
negative: Array<EdgeWithEvidence>, 
/**
 * Max confidence across all edges in the pair — used for sorting.
 */
max_confidence: number, };
