// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiffCounts = { nodes_added: number, nodes_removed: number, nodes_modified: number, edges_added: number, edges_removed: number, edges_modified: number, };
