// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentSearchResult } from "./DocumentSearchResult";

export type DocumentSearchOutput = { results: Array<DocumentSearchResult>, reasoning_applied: boolean, };
