// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageLocator } from "./PageLocator";
import type { UnitLocator } from "./UnitLocator";

export type DocumentReadSectionOutput = { doc_id: string, unit_id: string, section_id: string, title: string, locator: UnitLocator, page: PageLocator, text: string, citation: string, citation_safe: boolean, };
