// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DocumentSearchInput = { query: string, doc_ids: Array<string> | null, corpus: string | null, unit_types: Array<string> | null, top_k: number | null, };
