// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegalLocator } from "./LegalLocator";
import type { PageLocator } from "./PageLocator";

export type DocumentReadSectionOutput = { doc_id: string, unit_id: string, section_id: string, title: string, locator: LegalLocator, page: PageLocator, text: string, citation_safe: boolean, };
