// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageLocator } from "./PageLocator";
import type { UnitLocator } from "./UnitLocator";

export type DocumentSearchResult = { doc_id: string, section_id: string, unit_id: string | null, locator: UnitLocator | null, page: PageLocator, title: string, snippet: string, score_source: string, citation_safe: boolean, };
