// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitLocator } from "./UnitLocator";

export type DocumentReadSectionInput = { doc_id: string, locator: UnitLocator | null, section_id: string | null, label_norm: string | null, include_children: boolean | null, };
