// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageLocator } from "./PageLocator";
import type { UnitLocator } from "./UnitLocator";

export type DocumentQuoteOutput = { quote: string, citation: string, locator: UnitLocator, page: PageLocator, truncated: boolean, citation_safe: boolean, };
