// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegalLocator } from "./LegalLocator";
import type { PageLocator } from "./PageLocator";

export type DocumentSearchResult = { doc_id: string, section_id: string, unit_id: string | null, locator: LegalLocator | null, page: PageLocator, title: string, snippet: string, score_source: string, citation_safe: boolean, };
