// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegalLocator } from "./LegalLocator";
import type { PageLocator } from "./PageLocator";

export type DocumentQuoteOutput = { quote: string, citation: string, locator: LegalLocator, page: PageLocator, truncated: boolean, citation_safe: boolean, };
