// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DocumentResolveInput = { query: string | null, corpus: string | null, limit: number | null, };
