// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EdgeKind = "Influences" | "Causes" | "CorrelatesWith" | "DependsOn" | "DerivedFrom" | "Blocks" | "Improves" | "Degrades" | "OwnedBy" | "MeasuredBy" | "EvidencedBy" | "MentionedIn" | "DecidedBy" | "AssignedTo" | "InFunction" | "ForProduct" | "Impacts" | "NextAction" | "Contradicts" | "Corroborates";
