// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Confidence } from "./Confidence";
import type { EdgeId } from "./EdgeId";
import type { EdgeKind } from "./EdgeKind";
import type { EvidenceId } from "./EvidenceId";
import type { ExtractorKind } from "./ExtractorKind";
import type { NodeId } from "./NodeId";

/**
 * A directed edge in the knowledge graph.
 *
 * Invariant: `evidence` must be non-empty. `GraphStore::apply_mutation` rejects
 * `GraphMutation::UpsertEdge` with empty `evidence_ids` via `AxonMindError::EvidenceMissing`.
 * This is the single most important constraint in the system.
 */
export type Edge = { id: EdgeId, from: NodeId, to: NodeId, kind: EdgeKind, 
/**
 * Non-empty. At least one `EvidenceRef` required — enforced at store level.
 */
evidence: Array<EvidenceId>, confidence: Confidence, created_at: string, created_by: ExtractorKind, is_tainted: boolean, requires_human_review: boolean, };
