// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Edge } from "./Edge";
import type { Evidence } from "./Evidence";

/**
 * An edge together with all of its backing evidence citations.
 */
export type EdgeWithEvidence = { edge: Edge, evidence: Array<Evidence>, };
