// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Edge } from "./Edge";

export type EdgeChange = { 
/**
 * "(from_key)->(to_key):(edge_kind)" — the stable identity key.
 */
logical_key: string, before: Edge | null, after: Edge | null, changed_fields: Array<string>, };
