// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeId } from "./NodeId";

export type ExplainKpiInput = { kpi_id: NodeId, 
/**
 * How many hops of drivers/blockers to include in the rationale. Default: 2.
 */
depth: number | null, };
