// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Evidence } from "./Evidence";

export type ExplainKpiOutput = { 
/**
 * Rationale built from evidence quotes. Phase 3: LLM-generated and cached by (kpi_id, evidence_hash).
 * Phase 1: deterministic text assembled from evidence.quote fields.
 */
rationale: string, evidence: Array<Evidence>, confidence: number, };
