// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confidence defaults by extractor:
 * - `Manual`: 1.00 — user typed it, treated as ground truth
 * - `Connector`: 0.95 — structured field from a managed connector
 * - `Rule`: 0.85 — deterministic regex/schema match
 * - `Llm`: 0.50 — LLM-extracted, single source
 * - `Calculated`: inherits from sources (e.g. trend = min(confidence(t), confidence(t-1)))
 */
export type ExtractorKind = "Manual" | "Connector" | "Rule" | "Llm" | "Calculated";
