// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeId } from "./NodeId";

export type FindConflictsInput = { 
/**
 * Restrict to conflicts touching this node. Default: scan the whole graph.
 */
node_id: NodeId | null, 
/**
 * Max conflict pairs to return. Default: 50.
 */
limit: number | null, };
