// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeWithNodes } from "./EdgeWithNodes";
import type { Node } from "./Node";

export type FocusKpiOutput = { kpi: Node, 
/**
 * Edges with kind in {Influences, Improves, Causes} where to_id == kpi_id.
 */
drivers: Array<EdgeWithNodes>, 
/**
 * Edges with kind in {Blocks, Degrades} where to_id == kpi_id.
 */
blockers: Array<EdgeWithNodes>, 
/**
 * Outgoing edges from the KPI node where the target kind == Risk.
 */
risks: Array<EdgeWithNodes>, owner: Node | null, evidence_count: number, };
