// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeId } from "./EdgeId";
import type { NodeId } from "./NodeId";

export type GetEvidenceInput = { 
/**
 * Exactly one of edge_id or node_id must be set.
 */
edge_id: EdgeId | null, node_id: NodeId | null, };
