// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeKindCount } from "./NodeKindCount";

export type GraphStatsOutput = { total_nodes: number, document_nodes: number, concept_nodes: number, total_edges: number, total_evidence: number, avg_confidence: number, tainted_nodes: number, tainted_edges: number, review_required_nodes: number, nodes_by_kind: Array<NodeKindCount>, };
