// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffCounts } from "./DiffCounts";
import type { DiffSection } from "./DiffSection";
import type { EdgeChange } from "./EdgeChange";
import type { NodeChange } from "./NodeChange";

export type GraphDiff = { before_exported_at: string, after_exported_at: string, nodes: DiffSection<NodeChange>, edges: DiffSection<EdgeChange>, summary: DiffCounts, 
/**
 * Non-empty when the inputs were not cleanly diffable: logical-key collisions
 * (two distinct objects map to one key) or edges whose endpoints are absent from
 * the same export. These entries are dropped from the diff, so surface them rather
 * than silently hiding them.
 */
warnings: Array<string>, };
