// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node";
import type { SearchMatchKind } from "./SearchMatchKind";

export type GraphSearchOutput = { nodes: Array<Node>, 
/**
 * Which FTS5 columns matched for each result (parallel to `nodes`).
 */
matched_via: Array<Array<SearchMatchKind>>, };
