// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeKind } from "./NodeKind";

export type GraphSearchInput = { query: string, 
/**
 * Filter by node kind. Default: all kinds.
 */
kinds: Array<NodeKind> | null, 
/**
 * Maximum results. Default: 20.
 */
limit: number | null, };
