// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeId } from "./NodeId";

export type ImpactRadiusInput = { node_id: NodeId, 
/**
 * Maximum graph traversal depth. Default: 3.
 */
max_depth: number | null, };
