// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LegalLocator = { article: string | null, recital: string | null, section: string | null, paragraph: string | null, };
