// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node";

export type NodeChange = { 
/**
 * "(kind):(slugified_name)" — the stable identity key.
 */
logical_key: string, before: Node | null, after: Node | null, 
/**
 * Which fields differ; populated only for Modified entries.
 */
changed_fields: Array<string>, };
