// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable node identifier.
 *
 * ID strategy (matches soverex-open):
 * - Canonical business objects: deterministic slug set by the user or a rule.
 *   Examples: `"kpi.revenue_growth"`, `"team.engineering"`, `"doc.8f42a91c"`.
 * - Extracted/generated/proposed objects: `uuid::Uuid::new_v4().to_string()`.
 * - Document nodes: `format!("doc.{}", &sha256[..8])`.
 *
 * The slug prefix (`kpi.`, `doc.`, `team.`, etc.) is a convention, not enforced by the type.
 */
export type NodeId = string;
