// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A corpus whose package-declared `review_by` (retrieve_guarantee.md item 11) has passed —
 * powers the Library review UI's "currency review overdue" flag. Read live from installed
 * packages at call time (`[corpus]` meta is never persisted to a queryable table, same reason
 * `min_citation_provenance` isn't), not cached.
 */
export type OverdueCorpus = { corpus: string, package_name: string, 
/**
 * Package-declared verbatim (expected ISO-8601 `YYYY-MM-DD`; overdue is a lexicographic
 * string comparison against today, so a non-ISO value won't compare meaningfully).
 */
review_by: string, };
