// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReasoningSearchInput = { query: string, 
/**
 * Restrict results to these document node ids. None / empty = whole corpus.
 */
doc_node_ids: Array<string> | null, 
/**
 * Maximum results to return. Default: 20.
 */
max_results: number | null, };
