// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RetrievedSection } from "./RetrievedSection";

export type ReasoningSearchOutput = { sections: Array<RetrievedSection>, 
/**
 * false = BM25-only (no LLM provider present); true = LLM-reranked.
 */
reasoning_applied: boolean, };
