// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReasoningSearchInput = { query: string, 
/**
 * Restrict results to a single document. None = search whole corpus.
 */
doc_node_id: string | null, 
/**
 * Maximum results to return. Default: 20.
 */
max_results: number | null, };
