// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResolvedDocument = { doc_id: string, canonical_title: string, source_filename: string, aliases: Array<string>, language: string | null, corpus: Array<string>, confidence: number, };
