// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RetrievedSection = { 
/**
 * Bridges to the graph Document node (NodeKind::Document).
 */
doc_node_id: string, section_id: string, title: string, text: string, span_start: number, span_end: number, 
/**
 * Breadcrumb path from document root to this section.
 */
path: Array<string>, };
