// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KpiStatus } from "./KpiStatus";
import type { NodeId } from "./NodeId";

export type SuggestActionsInput = { kpi_id: NodeId, 
/**
 * Filter to only suggest actions relevant to these statuses. Default: all.
 */
status_filter: Array<KpiStatus> | null, 
/**
 * If false (default), exclude actions linked only through review-required edges.
 */
include_unreviewed: boolean | null, };
