// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeId } from "./NodeId";

export type TraceDecisionInput = { decision_node_id: NodeId, };
