// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeWithNodes } from "./EdgeWithNodes";
import type { Evidence } from "./Evidence";
import type { Node } from "./Node";

export type TraceDecisionOutput = { decision: Node, 
/**
 * Edges of kind DecidedBy or Causes pointing to this decision.
 */
caused_by: Array<EdgeWithNodes>, evidenced_by: Array<Evidence>, 
/**
 * Edges of kind NextAction from this decision.
 */
next_actions: Array<EdgeWithNodes>, };
