// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Arbitrary locator fields for a parsed unit (e.g. `article`/`paragraph` for a legal
 * instrument, `dosage`/`frequency` for a medical guideline) — whatever capture names a
 * structure package's grammar declares. A single-field tuple struct ("newtype") already
 * serializes transparently in JSON by default (no `#[serde(transparent)]` needed) — the wire
 * shape stays a flat object (`{"article":"33"}`), matching the pre-generic locator shape.
 */
export type UnitLocator = { [key in string]: string };
